- hosts: all
  become: yes

  tasks:
  - include_vars:
      dir: defaults
      extensions: ['yml']
  - include_vars:
      dir: vars
      extensions: ['yml']
  - include_tasks: tasks/main.yml

  handlers:
  - import_tasks: handlers/main.yml
