- become: no
  local_action:
    module: stat
    path: demo.key
  register: ssh_private_key

- assert:
    that:
      - ssh_private_key.stat.exists
    msg: 'Private key file `demo.key` must exist! Generate key pair with `ssh-keygen -t rsa -b 4096 -C "demo@dev.null" -f demo.key -N ""`'

- become: no
  local_action:
    module: stat
    path: demo.key.pub
  register: ssh_public_key

- assert:
    that:
      - ssh_public_key.stat.exists
    msg: 'Public key file `demo.key.pub` must exist! Generate key pair with `ssh-keygen -t rsa -b 4096 -C "demo@dev.null" -f demo.key -N ""`'

- set_fact:
    api_url: '{{ ansible_default_ipv4.address }}/{{ gitlab_api_root }}'

- name: install dependencies
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - curl
    - policycoreutils-python

- name: install gitlab gpg key
  rpm_key:
    state: present
    key: '{{ gitlab_gpg_key }}'

- name: install gitlab repo
  get_url:
    url: '{{ gitlab_repo_url }}'
    dest: /etc/yum.repos.d/gitlab-ce.repo
    owner: root
    group: root
    mode: 0644

- name: install gitlab
  package:
    name: 'gitlab-ce-{{ gitlab_version }}'
    state: present
  register: gitlab_install

- name: initiate configuration
  command: gitlab-ctl reconfigure
  when:
    - gitlab_install is defined
    - gitlab_install.changed

- name: configure gitlab
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify:
    - reconfigure gitlab
    - restart gitlab

# FIXME: https://gitlab.com/gitlab-org/gitlab-ce/issues/27954
- pause:
    prompt: "Sign into Gitlab | Settings > Access Tokens | Create an Personal Access Token with name 'api' | Enter API Key"
  when:
    - gitlab_private_token is not defined
    - gitlab_prompt_for_private_token
  register: gitlab_private_token_result

- set_fact:
    gitlab_private_token: '{{ gitlab_private_token_result.user_input }}'
  when:
    - gitlab_private_token is not defined
    - gitlab_private_token_result.user_input is defined

- include_tasks: users.yml

- include_tasks: ssh_keys.yml
  when: gitlab_private_token is defined

- include_tasks: projects.yml
  when: gitlab_private_token is defined
