# FIXME: https://gitlab.com/gitlab-org/gitlab-ce/issues/27954
- name: check for demo user
  uri:
    url: 'http://{{ api_url }}/users?search=demo'
    method: GET
    headers:
      PRIVATE-TOKEN: '{{ gitlab_private_token }}'
      Content-Type: 'application/json'
    status_code: 200
  when: gitlab_private_token is defined
  register: gitlab_user

- name: create demo user
  become_user: root
  command: "gitlab-rails runner -e production \"{{ lookup('file', 'create-user.rb') }}\""
  when: gitlab_private_token is not defined or gitlab_user.json|length == 0
